### ISSUE TITLE
An install failure on ionic technology stack when I tested the plugin, Error: already exists!

### ISSUE THREAD

**Issue by johnnynode** [jeremyup/cordova-plugin-x5-webview#5]
Error info:

```
Installing "cordova-plugin-x5-webview" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-x5-webview':CordovaError: Uh oh!
"/Users/../**/../platforms/android/src/org/jeremyup/cordova/x5engine/X5CookieManager.java" already ex
ists!
    at copyNewFile (/Users/../**/../platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Users/../**/../platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/../**/../platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/../**/../platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/../**/../platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/../**/../platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/../**/../platforms/android/cordova/node_modules/q/q.js:570:49
Error: Uh oh!
"/Users/../**/../platforms/android/src/org/jeremyup/cordova/x5engine/X5CookieManager.java" already exists!

```
Plugin list

```
$ cordova plugin ls
at.modalog.cordova.plugin.cache 1.1.0 "Cache"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-hot-code-push-plugin 1.5.3 "Hot Code Push Plugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-qqsdk 0.9.6 "QQSDK"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-wechat 2.1.0 "Wechat"cordova-plugin-weibosdk 0.6.1 "WeiboSDK"
cordova-plugin-whitelist 1.3.1 "Whitelist"cordova-plugin-x-toast 2.6.0 "Toast"
cordova-sqlite-storage 2.1.2 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```

plugin 'cordova-plugin-x5-webview 3.1.0 "X5 WebView Engine"' was added into the list at the same time, but it's not working and the index.js in that plugin package was missed,  I supposed that is there any wrong with some necessary configuration I missed? or whether there is a conflict with [this plugin :  ionic-native-transitions](https://github.com/shprink/ionic-native-transitions).

**Comment by johnnynode** [comment]
no response, will close it.
